/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GroupSection: typeof import('./src/components/GroupSection.vue')['default']
    LogConsole: typeof import('./src/components/LogConsole.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TemplatePicker: typeof import('./src/components/TemplatePicker.vue')['default']
    TunnelCard: typeof import('./src/components/TunnelCard.vue')['default']
    TunnelForm: typeof import('./src/components/TunnelForm.vue')['default']
    TunnelFormModal: typeof import('./src/components/TunnelFormModal.vue')['default']
    TunnelKindBadge: typeof import('./src/components/TunnelKindBadge.vue')['default']
    TunnelList: typeof import('./src/components/TunnelList.vue')['default']
    TunnelStatusIndicator: typeof import('./src/components/TunnelStatusIndicator.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    UTooltip: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
